fix load_engine function not defined
streamlit run demo_web.py 

```
File "/stable_diffusion.openvino/demo_web.py", line 123, in <module>
    engine = load_engine(args)
NameError: name 'load_engine' is not defined
```
found that the load_pipeline function is defined, but the load_engine function is called